---

- name: install ntpdate
  register: install
  apt: { name: ntpdate }

- name: configure ntpdate
  register: configure
  template:
    src: conf.j2
    dest: /etc/ntp.conf
    
- name: run after config
  when: install.changed or configure.changed
  failed_when: False
  command: ntpdate-debian

- name: setup crontab
  template:
    src: ntpdate.j2
    dest: /etc/cron.d/ntpdate
